[tool.poetry]
name = "logbattery"
version = "0.1.0"
description = ""
authors = ["Samuel Čavoj <samuel@cavoj.net>"]

[tool.poetry.dependencies]
python = "^3.8"
arrow = "^1.2.3"
tzlocal = "^4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
